server:
  port: 8088
spring:
  thymeleaf:
    cache: false
  application:
    name: second-hand-house  #全部小写
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/second_hand_house?characterEncoding=utf8&useSSL=false
      username: root
      password: root
          # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
#####################################################################################################
# mysql 属性配置
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://172.16.108.17:3306/wintop
#    username: root
#    password: wintop@2016
#  jpa:
#    show-sql: true
#####################################################################################################





#####################################################################################################
# mybatis mapper xml 配置
mybatis:
  # mybatis.type-aliases-package：指定domain类的基包，即指定其在*Mapper.xml文件中可以使用简名来代替全类名（看后边的UserMapper.xml介绍）
  type-aliases-package: com.wintop.ms.fs.*.mapper,com.wintop.ms.fs.*.entity
  mapper-locations: classpath:mybatis/mapper/*.xml,classpath:mybatis/mapper/*/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
#####################################################################################################



#####################################################################################################
# 打印日志
logging:
  level:
    root: INFO
    org.mybatis: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.springms: DEBUG
    org.springframework.cloud: debug
#####################################################################################################
#图片处理

cbs:
imagesPath : file:/C:/picFile/




